### ISSUE TITLE
Test gpt on something hard to know

### ISSUE THREAD

**Issue by CSUwangj** [oceanlvr/ChatGPT-ProBot#2]
/chatgpt Hello, Please use C# implement morph which transform player into duck in tModLoader.

**Comment by oceanlvr** [comment]
/chatgpt Hello, Please use C# implement morph which transform player into duck in tModLoader.

**Comment by oceanlvr** [comment]
@CSUwangj 555修好了  vercel serverless 计算只有10秒 麻了

**Comment by oceanlvr** [comment]
/chatgpt Can you tell me a bedtime story?

**Comment by CSUwangj** [comment]
/chatgpt Hello, Please use C# implement morph which using a buff transform player into duck in tModLoader.
